DROP TABLE WORD;
DROP TABLE SENTENCE;
DROP TABLE BOOK;

DROP SEQUENCE  BOOK_SEQ ;
DROP SEQUENCE  SENTENCE_SEQ ;
DROP SEQUENCE  WORD_SEQ ;

CREATE TABLE BOOK (
  idbook NUMBER (11,0) NOT NULL,
  title VARCHAR2(200) NOT NULL,
  content blob,
  PRIMARY KEY (idbook)
);

CREATE TABLE SENTENCE (
  idsentence NUMBER (11,0) NOT NULL,
  sentence VARCHAR2(500) DEFAULT NULL,
  book_idbook NUMBER (11) NOT NULL,
  PRIMARY KEY (idsentence),
  FOREIGN KEY (book_idbook) REFERENCES BOOK (idbook) ENABLE
);

CREATE TABLE WORD (
  idindex NUMBER (11,0) NOT NULL,
  word VARCHAR2(100) DEFAULT NULL,
  occurence NUMBER (11) DEFAULT NULL,
  PRIMARY KEY (idindex)
);

CREATE SEQUENCE BOOK_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;
CREATE SEQUENCE SENTENCE_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;
CREATE SEQUENCE WORD_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;

create user book identified by book;
grant all privileges to book identified by book;